console.log("Vi kan köpa hela Halmstad om vi vill");
console.log("Sug min röv");
a=3.14;
b=1+true;
console.log(b);
console.log(b+'hej');
x=2 + 'hej' + true;
console.log(x);
console.log("sug min röv");
console.log("svinigt");